"""
BACKTEST RL: WHAT BOT LOOKS FOR & LEARNS FROM
"""

print('=' * 80)
print('BACKTEST RL: WHAT BOT LOOKS FOR & LEARNS FROM')
print('=' * 80)

print('\n📊 AT EVERY SIGNAL (before entry decision):')
print('   Bot builds 13-feature RL state and sends to Cloud API:')
print('   1. entry_price - Actual entry price')
print('   2. price - Same as entry_price')
print('   3. vwap - Current VWAP value')
print('   4. vwap_distance - How far from VWAP (% above/below)')
print('   5. rsi - RSI indicator value (10 period)')
print('   6. atr - Average True Range volatility')
print('   7. vix - 15.0 (fixed for now)')
print('   8. hour - Time of day (0-23)')
print('   9. day_of_week - Monday=0, Sunday=6')
print('   10. volume_ratio - Current volume / 20-bar avg')
print('   11. recent_pnl - Sum of last 5 trades')
print('   12. streak - Consecutive wins (positive) or losses (negative)')
print('   13. side - LONG or SHORT')

print('\n🧠 CLOUD API PATTERN MATCHING (looks at ALL 6,880 experiences):')
print('   Step 1: Filter by signal type')
print('           LONG signal -> only compare to past LONG trades')
print('           SHORT signal -> only compare to past SHORT trades')
print('           Result: ~3,400 experiences per signal type')
print('')
print('   Step 2: Calculate similarity for EACH experience')
print('           Compares:')
print('           - RSI difference (how close is current RSI to past trade?)')
print('           - VWAP distance difference')
print('           - Time of day difference')
print('           - Volume ratio difference')
print('           - Hour similarity')
print('           - Day of week match')
print('')
print('   Step 3: Keep only highly similar matches (60%+ similarity)')
print('           Example: Out of 3,400 LONG experiences, maybe 15-100 are')
print('           60%+ similar to current conditions')
print('')
print('   Step 4: Calculate confidence from similar matches')
print('           - If 45 out of 50 similar trades won -> 90% confidence ✅')
print('           - If 12 out of 50 similar trades won -> 24% confidence ❌')
print('           - Threshold: Need 70% confidence to approve trade')

print('\n🎯 DECISION EXAMPLES:')
print('   Scenario A: Choppy low volume at lunch')
print('   - Current: RSI=65, volume_ratio=0.4, hour=12, streak=-2')
print('   - Cloud finds: 25 similar past trades, 20 were losses')
print('   - Confidence: 20% (way below 70% threshold)')
print('   - Decision: ❌ REJECTED - Bot learned to AVOID this setup')
print('')
print('   Scenario B: Trending market at open with volume')
print('   - Current: RSI=32, volume_ratio=1.8, hour=9, streak=3')
print('   - Cloud finds: 60 similar past trades, 52 were wins')
print('   - Confidence: 87% (above 70% threshold)')
print('   - Decision: ✅ APPROVED - Bot enters trade')

print('\n💾 WHAT GETS SAVED AFTER EACH TRADE:')
print('   File: cloud-api/signal_experience.json')
print('   Structure:')
print('   {')
print('     "timestamp": "2025-11-10T14:23:45",')
print('     "state": {')
print('       "entry_price": 5875.50,')
print('       "vwap": 5873.25,')
print('       "vwap_distance": 0.04,  # 0.04% above VWAP')
print('       "rsi": 32.5,')
print('       "atr": 12.3,')
print('       "vix": 15.0,')
print('       "hour": 14,')
print('       "day_of_week": 0,  # Monday')
print('       "volume_ratio": 1.4,  # 40% above avg volume')
print('       "recent_pnl": 2850.0,  # Last 5 trades +$2,850')
print('       "streak": 3,  # 3 consecutive wins')
print('       "side": "long"')
print('     },')
print('     "action": {')
print('       "took_trade": true,')
print('       "exploration_rate": 0.1')
print('     },')
print('     "reward": 625.0,  # P&L from this trade')
print('     "duration": 1842,  # Held 30.7 minutes')
print('     "execution": {')
print('       "exit_reason": "partial_3",  # Hit 5R target')
print('       "partial_fill": true,')
print('       "fill_ratio": 1.0')
print('     }')
print('   }')

print('\n🔄 LEARNING LOOP:')
print('   1. Backtest runs -> Generates signal')
print('   2. Bot builds 13-feature state')
print('   3. Cloud API finds similar past experiences')
print('   4. Cloud returns confidence (0-100%)')
print('   5. If confidence > 70% -> Enter trade')
print('   6. Trade executes with adaptive exits')
print('   7. Trade closes -> Bot saves complete experience to JSON')
print('   8. Next signal -> Cloud uses ALL experiences including new one')
print('   9. Repeat... bot gets smarter with each trade!')

print('\n📈 HOW BOT LEARNS AVOIDANCE:')
print('   - NOT hardcoded rules')
print('   - NOT "if choppy then skip"')
print('   - LEARNS from outcomes!')
print('')
print('   Example learning progression:')
print('   Trade 1: Lunch time, low volume -> Lost $187')
print('   Trade 5: Lunch time, low volume -> Lost $225')
print('   Trade 12: Lunch time, low volume -> Lost $156')
print('   Trade 15: Lunch time, low volume -> Won $412 (rare!)')
print('   Trade 23: Lunch time, low volume -> Lost $198')
print('')
print('   Pattern: 4 losses, 1 win = 20% win rate')
print('')
print('   Trade 50: NEW lunch signal appears')
print('   -> Cloud finds those 5 similar trades')
print('   -> Confidence = 20% (way below 70%)')
print('   -> Signal REJECTED ✅')
print('')
print('   Bot learned: "Lunch + low volume = bad" WITHOUT being told!')

print('\n✅ READY TO RUN:')
print('   - 6,880 signal experiences loaded')
print('   - 2,961 exit experiences for adaptive exits')
print('   - 13-feature state tracking')
print('   - Pattern matching across ALL experiences')
print('   - Saves to main signal_experience.json (not separate file)')
print('   - Bot learns from EVERY backtest trade')
print('=' * 80)
